# Generated by Django 3.2.9 on 2021-12-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sessionyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionYear',
        ),
    ]
