# Generated by Django 3.2.9 on 2022-01-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_staff_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_feedback',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
