# Generated by Django 3.2.9 on 2022-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_craeted_at_staff_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
