# Generated by Django 3.2.9 on 2022-02-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_attendance_attendancereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
