# Generated by Django 3.2.9 on 2022-02-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_student_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Notification',
        ),
    ]
