# Generated by Django 3.2.9 on 2022-02-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_student_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Feedback',
        ),
    ]
