# Generated by Django 5.2 on 2025-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_remove_staff_leave_data_remove_student_leave_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_leave",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_leave",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
