# Generated by Django 5.2 on 2025-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_staff_leave_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrollment_no",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
