# Generated by Django 5.2 on 2025-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_student_enrollment_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1st Semester"),
                    (2, "2nd Semester"),
                    (3, "3rd Semester"),
                    (4, "4th Semester"),
                    (5, "5th Semester"),
                    (6, "6th Semester"),
                    (7, "7th Semester"),
                    (8, "8th Semester"),
                ],
                null=True,
            ),
        ),
    ]
