# Generated by Django 5.2 on 2025-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_student_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="credit",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Credit"),
                    (2, "2 Credits"),
                    (3, "3 Credits"),
                    (4, "4 Credits"),
                ],
                null=True,
            ),
        ),
    ]
