# Generated by Django 5.2 on 2025-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_subject_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="subject_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
