# Generated by Django 5.2 on 2025-05-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_subject_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentresult",
            name="total_mark",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
